// Canonical registry of flagship Indian exams.
// Update next_date annually when official calendars are published.
// When adding a new exam, pick a short stable id (lowercase, underscore).
// Git history is the audit trail — no admin CRUD.

export type ExamEntry = {
  id: string
  name: string
  full_name: string
  next_date: string        // ISO date — update annually
  registration_window: string
  relevant_saathis: string[]
  syllabus_topics: string[]  // flat, 10-20 topics max
  source_url: string
  resources: {
    title: string
    url: string
    type: 'official' | 'notes' | 'papers' | 'mock'
    free: boolean
  }[]
}

export const EXAM_REGISTRY: ExamEntry[] = [
  {
    id: 'cat',
    name: 'CAT',
    full_name: 'Common Admission Test',
    next_date: '2026-11-29',
    registration_window: 'August–September 2026',
    relevant_saathis: ['bizsaathi', 'econsaathi', 'statssaathi', 'maathsaathi'],
    syllabus_topics: [
      'Quantitative Aptitude',
      'Data Interpretation',
      'Logical Reasoning',
      'Verbal Ability',
      'Reading Comprehension',
      'Number Systems',
      'Geometry & Mensuration',
      'Algebra',
      'Arithmetic',
      'Paragraph Summary',
    ],
    source_url: 'https://iimcat.ac.in',
    resources: [
      { title: 'Official CAT website', url: 'https://iimcat.ac.in', type: 'official', free: true },
      { title: 'Previous year papers', url: 'https://iimcat.ac.in/pages/previous-question-papers', type: 'papers', free: true },
    ],
  },
  {
    id: 'clat',
    name: 'CLAT',
    full_name: 'Common Law Admission Test',
    next_date: '2026-12-01',
    registration_window: 'October–November 2026',
    relevant_saathis: ['kanoonsaathi', 'polscisaathi', 'historysaathi'],
    syllabus_topics: [
      'English Language',
      'Current Affairs & GK',
      'Legal Reasoning',
      'Logical Reasoning',
      'Quantitative Techniques',
      'Constitutional Law Basics',
      'Contract Law Basics',
      'Comprehension Passages',
      'Fact Inference Judgment',
      'Critical Reasoning',
    ],
    source_url: 'https://consortiumofnlus.ac.in',
    resources: [
      { title: 'Official CLAT site', url: 'https://consortiumofnlus.ac.in', type: 'official', free: true },
      { title: 'Legal Bites CLAT prep', url: 'https://legalbites.in', type: 'notes', free: true },
    ],
  },
  {
    id: 'neet_ug',
    name: 'NEET UG',
    full_name: 'National Eligibility Entrance Test (Undergraduate)',
    next_date: '2026-05-03',
    registration_window: 'February–March 2026',
    relevant_saathis: ['medicosaathi', 'biosaathi', 'chemsaathi', 'physicsaathi'],
    syllabus_topics: [
      'Physics — Mechanics',
      'Physics — Thermodynamics',
      'Physics — Optics & Modern Physics',
      'Chemistry — Physical Chemistry',
      'Chemistry — Organic Chemistry',
      'Chemistry — Inorganic Chemistry',
      'Biology — Cell Biology',
      'Biology — Genetics & Evolution',
      'Biology — Human Physiology',
      'Biology — Ecology',
    ],
    source_url: 'https://nta.ac.in/neet',
    resources: [
      { title: 'NTA NEET official', url: 'https://nta.ac.in/neet', type: 'official', free: true },
    ],
  },
  {
    id: 'neet_pg',
    name: 'NEET PG',
    full_name: 'National Eligibility Entrance Test (Postgraduate)',
    next_date: '2026-03-15',
    registration_window: 'January 2026',
    relevant_saathis: ['medicosaathi', 'pharmasaathi'],
    syllabus_topics: [
      'Medicine & Allied Specialties',
      'Surgery & Allied Specialties',
      'Obstetrics & Gynaecology',
      'Paediatrics',
      'Preventive & Social Medicine',
      'Pharmacology',
      'Pathology',
      'Microbiology',
      'Anatomy',
      'Physiology',
    ],
    source_url: 'https://natboard.edu.in',
    resources: [
      { title: 'NBE official', url: 'https://natboard.edu.in', type: 'official', free: true },
    ],
  },
  {
    id: 'jee_main',
    name: 'JEE Main',
    full_name: 'Joint Entrance Examination Main',
    next_date: '2027-01-20',
    registration_window: 'November 2026',
    relevant_saathis: ['physicsaathi', 'chemsaathi', 'maathsaathi'],
    syllabus_topics: [
      'Physics — Mechanics',
      'Physics — Electricity & Magnetism',
      'Physics — Modern Physics',
      'Chemistry — Physical Chemistry',
      'Chemistry — Organic Chemistry',
      'Chemistry — Inorganic Chemistry',
      'Mathematics — Calculus',
      'Mathematics — Algebra',
      'Mathematics — Coordinate Geometry',
      'Mathematics — Trigonometry',
    ],
    source_url: 'https://jeemain.nta.ac.in',
    resources: [
      { title: 'JEE Main official', url: 'https://jeemain.nta.ac.in', type: 'official', free: true },
    ],
  },
  {
    id: 'jee_advanced',
    name: 'JEE Advanced',
    full_name: 'Joint Entrance Examination Advanced',
    next_date: '2026-05-24',
    registration_window: 'April–May 2026',
    relevant_saathis: ['physicsaathi', 'chemsaathi', 'maathsaathi'],
    syllabus_topics: [
      'Physics — Mechanics & Waves',
      'Physics — Optics & Modern Physics',
      'Physics — Electricity & Magnetism',
      'Chemistry — Physical Chemistry',
      'Chemistry — Organic Reactions',
      'Chemistry — Inorganic Chemistry',
      'Mathematics — Calculus & Differential Equations',
      'Mathematics — Algebra & Matrices',
      'Mathematics — Coordinate Geometry',
      'Mathematics — Probability & Statistics',
    ],
    source_url: 'https://jeeadv.ac.in',
    resources: [
      { title: 'JEE Advanced official', url: 'https://jeeadv.ac.in', type: 'official', free: true },
    ],
  },
  {
    id: 'gate',
    name: 'GATE',
    full_name: 'Graduate Aptitude Test in Engineering',
    next_date: '2027-02-07',
    registration_window: 'August–September 2026',
    relevant_saathis: ['mechsaathi', 'elecsaathi', 'electronicssaathi', 'compsaathi', 'civilsaathi', 'chemengg-saathi'],
    syllabus_topics: [
      'Engineering Mathematics',
      'General Aptitude',
      'Core Subject Paper 1',
      'Core Subject Paper 2',
      'Thermodynamics',
      'Fluid Mechanics',
      'Strength of Materials',
      'Control Systems',
      'Digital Electronics',
      'Data Structures & Algorithms',
    ],
    source_url: 'https://gate.iit.ac.in',
    resources: [
      { title: 'GATE official', url: 'https://gate.iit.ac.in', type: 'official', free: true },
    ],
  },
  {
    id: 'upsc_prelims',
    name: 'UPSC Prelims',
    full_name: 'UPSC Civil Services Preliminary Examination',
    next_date: '2026-06-07',
    registration_window: 'February–March 2026',
    relevant_saathis: ['historysaathi', 'polscisaathi', 'geosaathi', 'econsaathi', 'envirosaathi', 'kanoonsaathi'],
    syllabus_topics: [
      'Indian History & Culture',
      'Indian & World Geography',
      'Indian Polity & Governance',
      'Indian Economy',
      'Environment & Ecology',
      'Science & Technology',
      'Current Affairs',
      'General Science',
      'CSAT — Comprehension',
      'CSAT — Logical Reasoning & Maths',
    ],
    source_url: 'https://upsc.gov.in',
    resources: [
      { title: 'UPSC official', url: 'https://upsc.gov.in', type: 'official', free: true },
    ],
  },
  {
    id: 'upsc_mains',
    name: 'UPSC Mains',
    full_name: 'UPSC Civil Services Main Examination',
    next_date: '2026-09-20',
    registration_window: 'July–August 2026',
    relevant_saathis: ['historysaathi', 'polscisaathi', 'geosaathi', 'econsaathi', 'kanoonsaathi'],
    syllabus_topics: [
      'Essay Paper',
      'General Studies 1 — History & Society',
      'General Studies 2 — Governance & IR',
      'General Studies 3 — Economy & Environment',
      'General Studies 4 — Ethics',
      'Optional Paper 1',
      'Optional Paper 2',
      'Indian Language Paper',
      'English Paper',
      'Answer Writing Practice',
    ],
    source_url: 'https://upsc.gov.in',
    resources: [
      { title: 'UPSC official', url: 'https://upsc.gov.in', type: 'official', free: true },
    ],
  },
  {
    id: 'ssc_cgl',
    name: 'SSC CGL',
    full_name: 'Staff Selection Commission Combined Graduate Level',
    next_date: '2026-09-01',
    registration_window: 'June–July 2026',
    relevant_saathis: ['maathsaathi', 'econsaathi', 'statssaathi'],
    syllabus_topics: [
      'Quantitative Aptitude',
      'English Language',
      'General Intelligence & Reasoning',
      'General Awareness',
      'Statistics',
      'General Studies — Finance',
      'Data Analysis',
      'Arithmetic',
      'Geometry',
      'Algebra',
    ],
    source_url: 'https://ssc.nic.in',
    resources: [
      { title: 'SSC official', url: 'https://ssc.nic.in', type: 'official', free: true },
    ],
  },
  {
    id: 'ca_foundation',
    name: 'CA Foundation',
    full_name: 'Chartered Accountancy Foundation Examination',
    next_date: '2026-05-15',
    registration_window: 'January–February 2026',
    relevant_saathis: ['accountsaathi', 'finsaathi', 'econsaathi'],
    syllabus_topics: [
      'Principles & Practice of Accounting',
      'Business Laws',
      'Business Correspondence & Reporting',
      'Business Mathematics',
      'Logical Reasoning & Statistics',
      'Business Economics',
      'Business & Commercial Knowledge',
      'Journal & Ledger',
      'Partnership Accounts',
      'Company Accounts',
    ],
    source_url: 'https://icai.org',
    resources: [
      { title: 'ICAI official', url: 'https://icai.org', type: 'official', free: true },
    ],
  },
  {
    id: 'ugc_net',
    name: 'UGC NET',
    full_name: 'University Grants Commission National Eligibility Test',
    next_date: '2026-06-15',
    registration_window: 'March–April 2026',
    relevant_saathis: ['historysaathi', 'psychsaathi', 'econsaathi', 'polscisaathi', 'geosaathi'],
    syllabus_topics: [
      'Teaching & Research Aptitude',
      'Reasoning Ability',
      'Comprehension',
      'Divergent Thinking',
      'Communication',
      'ICT in Education',
      'People & Environment',
      'Higher Education System',
      'Subject Paper — Core Topics',
      'Research Methodology',
    ],
    source_url: 'https://ugcnet.nta.ac.in',
    resources: [
      { title: 'UGC NET official', url: 'https://ugcnet.nta.ac.in', type: 'official', free: true },
    ],
  },
  {
    id: 'gre',
    name: 'GRE',
    full_name: 'Graduate Record Examination',
    next_date: '2026-12-31',
    registration_window: 'Year-round',
    relevant_saathis: ['maathsaathi', 'statssaathi', 'econsaathi'],
    syllabus_topics: [
      'Verbal Reasoning',
      'Quantitative Reasoning',
      'Analytical Writing',
      'Vocabulary in Context',
      'Reading Comprehension',
      'Text Completion',
      'Sentence Equivalence',
      'Arithmetic & Algebra',
      'Geometry & Data Analysis',
      'Issue & Argument Essays',
    ],
    source_url: 'https://ets.org/gre',
    resources: [
      { title: 'ETS GRE official', url: 'https://ets.org/gre', type: 'official', free: true },
    ],
  },
  {
    id: 'gmat',
    name: 'GMAT',
    full_name: 'Graduate Management Admission Test',
    next_date: '2026-12-31',
    registration_window: 'Year-round',
    relevant_saathis: ['bizsaathi', 'maathsaathi', 'econsaathi'],
    syllabus_topics: [
      'Quantitative Reasoning',
      'Verbal Reasoning',
      'Data Insights',
      'Analytical Writing',
      'Critical Reasoning',
      'Reading Comprehension',
      'Sentence Correction',
      'Data Sufficiency',
      'Problem Solving',
      'Integrated Reasoning',
    ],
    source_url: 'https://mba.com/gmat',
    resources: [
      { title: 'GMAT official', url: 'https://mba.com/gmat', type: 'official', free: true },
    ],
  },
  {
    id: 'fmge',
    name: 'FMGE',
    full_name: 'Foreign Medical Graduate Examination',
    next_date: '2026-06-20',
    registration_window: 'April–May 2026',
    relevant_saathis: ['medicosaathi'],
    syllabus_topics: [
      'Anatomy',
      'Physiology',
      'Biochemistry',
      'Pharmacology',
      'Pathology',
      'Microbiology',
      'Medicine',
      'Surgery',
      'Obstetrics & Gynaecology',
      'Preventive & Social Medicine',
    ],
    source_url: 'https://natboard.edu.in',
    resources: [
      { title: 'NBE FMGE official', url: 'https://natboard.edu.in', type: 'official', free: true },
    ],
  },
]

export function getExamById(id: string): ExamEntry | undefined {
  return EXAM_REGISTRY.find((e) => e.id === id)
}

export function getExamsForSaathi(slug: string): ExamEntry[] {
  return EXAM_REGISTRY.filter((e) => e.relevant_saathis.includes(slug))
}
