import type { Saathi } from '@/types'

export type SaathiWithDescription = Saathi & {
  description: string
  isLive: boolean
}

export const SAATHIS: SaathiWithDescription[] = [
  {
    id: 'kanoonsaathi',
    name: 'KanoonSaathi',
    emoji: '⚖️',
    tagline: 'Where law meets intelligence',
    primary: '#1E3A5F',
    accent: '#3B82F6',
    bg: '#E8F0FE',
    theme: 'legal',
    isLive: true,
    description: `I know the Indian legal system inside out — from constitutional law to criminal procedure, from CLAT preparation to LLM research. I speak the language of Indian courts, connect today's judgements to your syllabus, and never give legal advice — only legal education.`,
  },
  {
    id: 'maathsaathi',
    name: 'MaathSaathi',
    emoji: '📐',
    tagline: 'Numbers made neighbourly',
    primary: '#0F4C2A',
    accent: '#22C55E',
    bg: '#EAF3DE',
    isLive: true,
    description: `Numbers are my language and yours too — you just haven't found the right dialect yet. Whether you're wrestling with calculus, preparing for GATE, or chasing a research problem, I meet you where the confusion lives and walk you through to clarity.`,
  },
  {
    id: 'chemsaathi',
    name: 'ChemSaathi',
    emoji: '🧪',
    tagline: 'Reactions decoded, concepts unlocked',
    primary: '#5C1A6B',
    accent: '#A855F7',
    bg: '#F5E8FE',
    isLive: true,
    has3D: true,
    description: `Pure chemistry — from organic reactions to quantum models of bonding. I'm for B.Sc and M.Sc Chemistry students, CSIR-NET aspirants, and anyone who wants to understand why molecules behave the way they do. Not the engineering side — the science.`,
  },
  {
    id: 'biosaathi',
    name: 'BioSaathi',
    emoji: '🧬',
    tagline: 'Life explained, cell by cell',
    primary: '#1A5C2E',
    accent: '#10B981',
    bg: '#E6F7EC',
    isLive: true,
    has3D: true,
    description: `Life is my subject — at every scale. From cell biology to evolutionary genetics, from NEET preparation to PhD-level research, I connect the mechanisms of living systems to your specific questions, your exams, and your research dreams.`,
  },
  {
    id: 'pharmasaathi',
    name: 'PharmaSaathi',
    emoji: '💊',
    tagline: 'Every molecule has a story',
    primary: '#7A1C1C',
    accent: '#EF4444',
    bg: '#FDEAEA',
    isLive: true,
    has3D: true,
    description: `Every drug has a story — from molecule to mechanism to patient outcome. I guide B.Pharm and M.Pharm students through pharmacology, pharmaceutics, and drug design, with awareness of Indian pharmacy regulations and the GTU/Mumbai University syllabus.`,
  },
  {
    id: 'medicosaathi',
    name: 'MedicoSaathi',
    emoji: '🏥',
    tagline: 'Healing starts with understanding',
    primary: '#1A4A5C',
    accent: '#0EA5E9',
    bg: '#E4F0F5',
    isLive: true,
    has3D: true,
    description: `Medicine is both art and science — I help with the science so you can focus on the art. From Anatomy in 1st MBBS to clinical reasoning in final year, I know the Indian medical curriculum, the NEXT exam pattern, and where students most often struggle.`,
  },
  {
    id: 'nursingsaathi',
    name: 'NursingSaathi',
    emoji: '🩺',
    tagline: 'Care grounded in knowledge',
    primary: '#5C001A',
    accent: '#F43F5E',
    bg: '#FCEAF0',
    isLive: true,
    description: `Care begins with knowledge, and knowledge begins with understanding why — not just what. I support B.Sc Nursing, GNM, and ANM students through pharmacology, clinical procedures, and the practical reasoning that makes the difference at the bedside.`,
  },
  {
    id: 'psychsaathi',
    name: 'PsychSaathi',
    emoji: '🧠',
    tagline: 'Understanding minds, building empathy',
    primary: '#3A1C5C',
    accent: '#8B5CF6',
    bg: '#F0E8FC',
    isLive: true,
    description: `The mind is the most complex system ever studied — and the most misunderstood. I explore psychology with you: theories, research methods, abnormal psychology, counselling approaches. I am a learning companion, never a therapist or diagnostician.`,
  },
  {
    id: 'mechsaathi',
    name: 'MechSaathi',
    emoji: '⚙️',
    tagline: 'Engineering minds, precision built',
    primary: '#1A3A5C',
    accent: '#0EA5E9',
    bg: '#E6EEF8',
    isLive: true,
    has3D: true,
    description: `Mechanical engineering is how the physical world is shaped — and I know every corner of it. Thermodynamics, fluid mechanics, machine design, manufacturing — I connect your GTU or VTU syllabus to real engineering problems and your career ahead.`,
  },
  {
    id: 'civilsaathi',
    name: 'CivilSaathi',
    emoji: '🏗️',
    tagline: 'Structures that stand the test of time',
    primary: '#3A2800',
    accent: '#F59E0B',
    bg: '#FFF3E0',
    isLive: true,
    has3D: true,
    description: `Buildings, bridges, and the infrastructure that holds civilisation together — this is my domain. Structural analysis, soil mechanics, construction management, and GATE Civil prep. I understand the Indian construction context and the regulatory environment you'll work in.`,
  },
  {
    id: 'elecsaathi',
    name: 'ElecSaathi',
    emoji: '⚡',
    tagline: 'Current knowledge, grounded thinking',
    primary: '#003A5C',
    accent: '#06B6D4',
    bg: '#E0F0FA',
    isLive: true,
    has3D: true,
    description: `Electrical power — generation, transmission, machines, and control systems. Not to be confused with electronics. I'm for Electrical Engineering students at IITs, NITs, and state universities, connecting power systems theory to the Indian energy sector you'll enter.`,
  },
  {
    id: 'compsaathi',
    name: 'CompSaathi',
    emoji: '💻',
    tagline: 'Code, conquer, create',
    primary: '#1C1C5C',
    accent: '#6366F1',
    bg: '#EEEEF8',
    isLive: true,
    description: `Code is a tool — thinking is the skill. I help Computer Science students master algorithms, data structures, operating systems, and AI fundamentals, while connecting your learning to industry reality, research opportunities, and the career you're building.`,
  },
  {
    id: 'envirosathi',
    name: 'EnviroSaathi',
    emoji: '🌍',
    tagline: 'Engineering a sustainable tomorrow',
    primary: '#0F3A1A',
    accent: '#84CC16',
    bg: '#E4F5E8',
    isLive: true,
    description: `The planet's most urgent problems are engineering problems — and you're training to solve them. Environmental science, sustainability engineering, climate systems, and environmental law: I connect your curriculum to India's environmental challenges.`,
  },
  {
    id: 'bizsaathi',
    name: 'BizSaathi',
    emoji: '📈',
    tagline: 'Business thinking, sharpened daily',
    primary: '#1A3A00',
    accent: '#65A30D',
    bg: '#EEF8E4',
    isLive: true,
    description: `Business is about decisions under uncertainty — and I help you build the frameworks to decide well. Management theory, strategy, operations, entrepreneurship. Whether you're in BBA, MBA, or preparing for CAT, I think like a business educator who's also read the case studies.`,
  },
  {
    id: 'finsaathi',
    name: 'FinSaathi',
    emoji: '💰',
    tagline: 'Money matters, demystified',
    primary: '#1A3A2A',
    accent: '#059669',
    bg: '#E4F5EE',
    isLive: true,
    description: `Money moves through systems — and understanding those systems changes how you see the world. From B.Com fundamentals to CA Foundation, from corporate finance to RBI policy: I explain finance the way it actually works, not just the way textbooks present it.`,
  },
  {
    id: 'mktsaathi',
    name: 'MktSaathi',
    emoji: '📣',
    tagline: 'From insight to influence',
    primary: '#5C1A00',
    accent: '#F97316',
    bg: '#FFF0E8',
    isLive: true,
    description: `Marketing is how value finds the people who need it. Consumer behaviour, brand strategy, digital marketing, and market research — I connect MBA marketing theory to Indian consumer reality and the campaigns you'll actually run in your career.`,
  },
  {
    id: 'hrsaathi',
    name: 'HRSaathi',
    emoji: '🤝',
    tagline: 'People first, always',
    primary: '#3A003A',
    accent: '#EC4899',
    bg: '#F8E8F8',
    isLive: true,
    description: `Organisations are people — and people are complex. I cover HR management, organisational behaviour, labour law, and talent strategy with an eye on the Indian workplace context, the factories and offices where HR actually happens, not just the textbook version.`,
  },
  {
    id: 'archsaathi',
    name: 'ArchSaathi',
    emoji: '🏛️',
    tagline: 'Design thinking, built different',
    primary: '#6B4A00',
    accent: '#D97706',
    bg: '#FFF4D6',
    isLive: true,
    description: `Architecture is frozen music — and I help you hear the notes. Design theory, building technology, urban planning, and the history of spaces that shaped civilisations. I support B.Arch students through studio thinking and technical knowledge equally.`,
  },
  {
    id: 'historysaathi',
    name: 'HistorySaathi',
    emoji: '🏺',
    tagline: 'Every era has a lesson',
    primary: '#5C3A00',
    accent: '#B45309',
    bg: '#FFF0E0',
    isLive: true,
    description: `History is not the past — it's the key to understanding the present. From ancient civilisations to modern India, from UPSC History optional to academic research, I connect what happened to why it matters for the world you're living in right now.`,
  },
  {
    id: 'econsaathi',
    name: 'EconSaathi',
    emoji: '📊',
    tagline: 'Markets explained, policies demystified',
    primary: '#2C4A00',
    accent: '#4D7C0F',
    bg: '#EEF6E0',
    isLive: true,
    description: `Economics explains almost everything — if you know how to read it. Micro and macro theory, Indian economic policy, RBI decisions, trade, development economics, and UPSC Economics optional: I make the abstract tangible and the tangible meaningful.`,
  },
  {
    id: 'chemengg saathi',
    name: 'ChemEnggSaathi',
    emoji: '⚗️',
    tagline: 'Where chemistry meets industry',
    primary: '#7C2D12',
    accent: '#EA580C',
    bg: '#FFF1E6',
    isLive: true,
    description: `Chemical engineering turns chemistry into industry — and industry into civilisation. Fluid mechanics, heat transfer, reaction engineering, process design: I know the difference between a chemist and a chemical engineer, and I teach to that difference. GTU, VTU, and NIT syllabi are home to me.`,
  },
  {
    id: 'biotechsaathi',
    name: 'BioTechSaathi',
    emoji: '🦠',
    tagline: 'Engineering life, one cell at a time',
    primary: '#064E3B',
    accent: '#10B981',
    bg: '#ECFDF5',
    isLive: true,
    description: `Biotechnology is where biology becomes engineering — and the possibilities are limitless. Genetic engineering, fermentation, bioprocess design, bioinformatics: I guide B.Tech Biotechnology students through the science and toward the careers and research opportunities emerging in India's biotech sector.`,
  },
  {
    id: 'aerospacesaathi',
    name: 'AerospaceSaathi',
    emoji: '✈️',
    tagline: 'From ground to orbit, engineered',
    primary: '#1E3A5F',
    accent: '#3B82F6',
    bg: '#EFF6FF',
    isLive: true,
    has3D: true,
    description: `From Bernoulli to orbital mechanics — aerospace engineering is humanity's most ambitious discipline. Aerodynamics, propulsion, structures, avionics, and space technology: I support students at IITs, IIST, and private universities, with awareness of ISRO, DRDO, and the growing Indian aerospace industry.`,
  },
  {
    id: 'electronicssaathi',
    name: 'ElectronicsSaathi',
    emoji: '📡',
    tagline: 'Signals, systems, and beyond',
    primary: '#312E81',
    accent: '#6366F1',
    bg: '#EEF2FF',
    isLive: true,
    has3D: true,
    description: `Signals, circuits, and systems — the invisible infrastructure of modern life. Analog circuits, digital systems, VLSI, communication systems, embedded electronics: I cover Electronics Engineering for students who want depth in circuits and signals, not software development.`,
  },
  {
    id: 'physicsaathi',
    name: 'PhysicsSaathi',
    emoji: '⚛️',
    tagline: 'Forces, fields, and the fabric of reality',
    primary: '#1A2A5C',
    accent: '#818CF8',
    bg: '#EEEEF8',
    isLive: true,
    has3D: true,
    description: `Physics is the language the universe uses to describe itself. From Newtonian mechanics to quantum fields, from JEE preparation to GATE PH and IIT JAM, I help you develop the deep physical intuition that separates someone who solves problems from someone who merely remembers formulas.`,
  },
  {
    id: 'accountsaathi',
    name: 'AccountSaathi',
    emoji: '📒',
    tagline: 'Every debit has a story, every credit a reason',
    primary: '#1A3A2A',
    accent: '#34D399',
    bg: '#E4F5EE',
    isLive: true,
    description: `Accounting is the language of business decisions — and I make sure you speak it fluently. From Class 11-12 fundamentals to CA Foundation and CA Inter, from financial statements to cost accounting, I know the ICAI syllabus and the practical reasoning that examiners reward.`,
  },
  {
    id: 'polscisaathi',
    name: 'PolSciSaathi',
    emoji: '🏛️',
    tagline: 'Power, policy, and the politics of ideas',
    primary: '#2A1A5C',
    accent: '#A78BFA',
    bg: '#EEEEF8',
    isLive: true,
    description: `Political science is the study of power — how it is claimed, contested, and constrained. From B.A Political Science to UPSC GS2, from Indian polity to international relations, I connect theoretical frameworks to the living politics you see in today's headlines.`,
  },
  {
    id: 'statssaathi',
    name: 'StatsSaathi',
    emoji: '📊',
    tagline: 'Data speaks. Statistics gives it a voice.',
    primary: '#1A2A4A',
    accent: '#38BDF8',
    bg: '#E4F0F8',
    isLive: true,
    description: `Statistics is not just maths — it is structured reasoning about uncertainty. From B.Sc Statistics to IIT JAM, from probability theory to data science applications, I bridge the gap between the formulae in your textbook and the decisions they actually enable in the real world.`,
  },
  {
    id: 'geosaathi',
    name: 'GeoSaathi',
    emoji: '🌍',
    tagline: 'Every map tells a story of the earth and its people',
    primary: '#0F3A1A',
    accent: '#4ADE80',
    bg: '#E4F5E8',
    isLive: true,
    description: `Geography connects the physical world to the human world — and both to your exams. Physical geography, human geography, and cartography for B.A and B.Sc students, with deep coverage of UPSC GS1 and the optional paper, including map-based questions and India's geographic context.`,
  },
  {
    id: 'agrisaathi',
    name: 'AgriSaathi',
    emoji: '🌾',
    tagline: 'From seed to harvest — science meets the soil',
    primary: '#2A1A00',
    accent: '#F59E0B',
    bg: '#FFF3E0',
    isLive: true,
    description: `Agriculture feeds India — and understanding it deeply is both a career and a responsibility. From B.Sc Agriculture and Horticulture to ICAR NET and State PSC exams, I connect agronomy, soil science, crop physiology, and agricultural economics to the land and the market you'll work in.`,
  },
]
