// Subject chips (curriculum topics) per Saathi — up to 12 per saathi
// Students select up to 5. The chip that matches their Saathi is shown by default.

export const SUBJECT_CHIPS: Record<string, string[]> = {
  kanoonsaathi: [
    'Constitutional Law',
    'Criminal Law',
    'Civil Law',
    'Contract Law',
    'Evidence Law',
    'Family Law',
    'Administrative Law',
    'Corporate Law',
    'IPR',
    'International Law',
    'Labour Law',
    'Tax Law',
  ],
  maathsaathi: [
    'Calculus',
    'Linear Algebra',
    'Probability',
    'Statistics',
    'Differential Equations',
    'Real Analysis',
    'Discrete Maths',
    'Mechanics',
    'Number Theory',
    'Abstract Algebra',
    'Complex Analysis',
    'Topology',
  ],
  pharmasaathi: [
    'Pharmacology I',
    'Pharmacology II',
    'Pharmaceutics',
    'Pharmaceutical Chemistry',
    'Pharmacognosy',
    'Drug Analysis',
    'Biopharmaceutics',
    'Clinical Pharmacy',
    'Medicinal Chemistry',
    'Quality Assurance',
    'Regulatory Affairs',
    'Pharmacokinetics',
  ],
  chemsaathi: [
    'Organic Chemistry',
    'Inorganic Chemistry',
    'Physical Chemistry',
    'Analytical Chemistry',
    'Spectroscopy',
    'Biochemistry',
    'Polymer Chemistry',
    'Electronic Structure',
    'Reaction Mechanisms',
    'Thermodynamics',
    'Electrochemistry',
    'Chemical Kinetics',
  ],
  biosaathi: [
    'Cell Biology',
    'Molecular Biology',
    'Genetics',
    'Biochemistry',
    'Ecology',
    'Evolution',
    'Microbiology',
    'Physiology',
    'Immunology',
    'Developmental Biology',
    'Neuroscience',
    'Systems Biology',
  ],
  medicosaathi: [
    'Anatomy',
    'Physiology',
    'Biochemistry',
    'Pathology',
    'Pharmacology',
    'Microbiology',
    'Community Medicine',
    'Surgery',
    'Medicine',
    'Obstetrics',
    'Paediatrics',
    'Forensic Medicine',
  ],
  nursingsaathi: [
    'Fundamentals of Nursing',
    'Medical-Surgical Nursing',
    'Paediatric Nursing',
    'Obstetric Nursing',
    'Psychiatric Nursing',
    'Community Health Nursing',
    'Nursing Pharmacology',
    'Critical Care Nursing',
    'Anatomy & Physiology',
    'Nutrition & Dietetics',
    'Microbiology',
    'First Aid & Emergency Care',
  ],
  psychsaathi: [
    'General Psychology',
    'Developmental Psychology',
    'Abnormal Psychology',
    'Social Psychology',
    'Cognitive Psychology',
    'Personality Theories',
    'Research Methods',
    'Psychological Testing',
    'Neuropsychology',
    'Counselling Psychology',
    'Health Psychology',
    'Positive Psychology',
  ],
  compsaathi: [
    'Data Structures',
    'Algorithms',
    'Operating Systems',
    'Database Management',
    'Computer Networks',
    'Software Engineering',
    'Theory of Computation',
    'Computer Architecture',
    'Compiler Design',
    'Machine Learning',
    'Cloud Computing',
    'Cybersecurity',
  ],
  mechsaathi: [
    'Engineering Mechanics',
    'Thermodynamics',
    'Fluid Mechanics',
    'Manufacturing Processes',
    'Machine Design',
    'Strength of Materials',
    'Heat Transfer',
    'CAD/CAM',
    'Robotics',
    'Vibrations',
    'Metrology',
    'Industrial Engineering',
  ],
  civilsaathi: [
    'Structural Analysis',
    'Soil Mechanics',
    'Fluid Mechanics',
    'Concrete Technology',
    'Transportation Engineering',
    'Surveying',
    'Environmental Engineering',
    'Hydraulics',
    'Foundation Engineering',
    'Steel Structures',
    'Construction Management',
    'Geotechnical Engineering',
  ],
  archsaathi: [
    'Architectural Design',
    'Building Technology',
    'Urban Planning',
    'History of Architecture',
    'Environmental Design',
    'Structural Systems',
    'Interior Architecture',
    'Landscape Design',
    'Building Services',
    'Housing Design',
    'Vernacular Architecture',
    'Digital Architecture',
  ],
  elecsaathi: [
    'Circuit Theory',
    'Signals & Systems',
    'Control Systems',
    'Power Systems',
    'Power Electronics',
    'Electric Machines',
    'Electromagnetics',
    'Analog Circuits',
    'Digital Systems',
    'VLSI Design',
    'Embedded Systems',
    'Energy Systems',
  ],
  electronicssaathi: [
    'Analog Electronics',
    'Digital Electronics',
    'Microprocessors',
    'Signal Processing',
    'Communication Systems',
    'VLSI',
    'Embedded Systems',
    'Control Engineering',
    'RF Electronics',
    'Sensors',
    'IoT',
    'Semiconductor Devices',
  ],
  chemenggsaathi: [
    'Chemical Process Calculations',
    'Thermodynamics',
    'Fluid Operations',
    'Heat Transfer',
    'Mass Transfer',
    'Chemical Reaction Engineering',
    'Process Control',
    'Transport Phenomena',
    'Plant Design',
    'Safety Engineering',
    'Polymer Technology',
    'Environmental Engineering',
  ],
  biotechsaathi: [
    'Molecular Biology',
    'Biochemistry',
    'Microbiology',
    'Cell Biology',
    'Bioprocess Engineering',
    'Bioinformatics',
    'Genetic Engineering',
    'Immunology',
    'Biotechnology Regulation',
    'Bioseparation',
    'Enzyme Technology',
    'Fermentation Technology',
  ],
  aerospacesaathi: [
    'Orbital Mechanics',
    'Spacecraft Design',
    'Propulsion',
    'Aerodynamics',
    'Structures & Materials',
    'Attitude Control',
    'Space Mission Design',
    'Guidance Navigation',
    'Avionics',
    'Thermal Control',
    'Remote Sensing',
    'Launch Vehicles',
  ],
  econsaathi: [
    'Microeconomics',
    'Macroeconomics',
    'Econometrics',
    'International Trade',
    'Development Economics',
    'Public Finance',
    'Monetary Economics',
    'Industrial Organisation',
    'Game Theory',
    'Labour Economics',
    'Environmental Economics',
    'Financial Economics',
  ],
  bizsaathi: [
    'Management Principles',
    'Marketing Management',
    'Finance',
    'Human Resources',
    'Operations Management',
    'Business Strategy',
    'Accounting',
    'Business Law',
    'Entrepreneurship',
    'Organisational Behaviour',
    'Supply Chain',
    'Business Analytics',
  ],
  finsaathi: [
    'Financial Management',
    'Security Analysis',
    'Portfolio Management',
    'Derivatives',
    'Fixed Income',
    'Corporate Finance',
    'Financial Modelling',
    'Risk Management',
    'Accounting',
    'Banking',
    'Fintech',
    'International Finance',
  ],
  mktsaathi: [
    'Marketing Management',
    'Consumer Behaviour',
    'Brand Management',
    'Digital Marketing',
    'Advertising & Promotion',
    'Market Research',
    'Sales Management',
    'Product Management',
    'Retail Marketing',
    'International Marketing',
    'Services Marketing',
    'Marketing Analytics',
  ],
  hrsaathi: [
    'Human Resource Management',
    'Organisational Behaviour',
    'Labour Law',
    'Recruitment & Selection',
    'Training & Development',
    'Performance Management',
    'Compensation & Benefits',
    'Industrial Relations',
    'HR Analytics',
    'Talent Management',
    'Change Management',
    'Strategic HRM',
  ],
  historysaathi: [
    'Ancient India',
    'Medieval India',
    'Modern India',
    'World History',
    'Art & Culture',
    'Indian Nationalism',
    'Post-Independence India',
    'Economic History',
    'Social History',
    'Historiography',
    'Regional History',
    'Constitutional History',
  ],
  accountsaathi: [
    'Financial Accounting',
    'Cost Accounting',
    'Management Accounting',
    'Taxation — Direct',
    'Taxation — Indirect (GST)',
    'Auditing',
    'Corporate Accounting',
    'Accounting Standards (Ind AS)',
    'Financial Statements',
    'Partnership Accounts',
    'Company Law Basics',
    'Tally & Accounting Software',
  ],
  polscisaathi: [
    'Indian Political System',
    'Constitutional Government',
    'Comparative Politics',
    'International Relations',
    'Political Theory',
    'Public Administration',
    'Indian Foreign Policy',
    'Political Ideologies',
    'Electoral Politics',
    'Federalism',
    'Local Self Government',
    'UPSC Political Science',
  ],
  statssaathi: [
    'Probability Theory',
    'Descriptive Statistics',
    'Inferential Statistics',
    'Regression Analysis',
    'Time Series',
    'Statistical Quality Control',
    'Sampling Theory',
    'Bayesian Statistics',
    'Non-Parametric Methods',
    'Design of Experiments',
    'Multivariate Analysis',
    'Data Science Foundations',
  ],
  geosaathi: [
    'Physical Geography',
    'Human Geography',
    'Indian Geography',
    'World Geography',
    'Climatology',
    'Geomorphology',
    'Oceanography',
    'Population Geography',
    'Economic Geography',
    'Political Geography',
    'Remote Sensing & GIS',
    'UPSC Geography Optional',
  ],
  agrisaathi: [
    'Agronomy',
    'Soil Science',
    'Plant Physiology',
    'Agricultural Botany',
    'Agricultural Chemistry',
    'Horticulture',
    'Plant Pathology',
    'Agricultural Entomology',
    'Animal Husbandry',
    'Agricultural Economics',
    'Farm Management',
    'Agricultural Extension',
  ],
  // ID matches saathis.ts: 'envirosathi' (no second 'a')
  envirosathi: [
    'Environmental Chemistry',
    'Ecology',
    'Climate Science',
    'Environmental Policy',
    'Sustainability',
    'Water Resources',
    'Air Quality',
    'Solid Waste Management',
    'Environmental Impact',
    'Renewable Energy',
    'Pollution Control',
    'Geography',
  ],
  physicsaathi: [
    'Classical Mechanics',
    'Electromagnetism',
    'Quantum Mechanics',
    'Thermodynamics',
    'Statistical Mechanics',
    'Optics',
    'Nuclear Physics',
    'Particle Physics',
    'Condensed Matter',
    'Astrophysics',
    'Mathematical Physics',
    'Relativity',
  ],
}

// Interest area chips — more exploratory/research-oriented, per saathi
export const INTEREST_CHIPS: Record<string, string[]> = {
  kanoonsaathi: [
    'Constitutional Reforms',
    'Human Rights',
    'Cyber Law',
    'Environmental Law',
    'Legal Tech',
    'International Criminal Law',
    'AI & Law',
    'Gender Justice',
  ],
  maathsaathi: [
    'Cryptography',
    'Mathematical Modelling',
    'Game Theory',
    'Competitive Maths',
    'Quantum Computing',
    'Data Science',
    'Actuarial Science',
    'Mathematical Finance',
  ],
  pharmasaathi: [
    'Drug Discovery',
    'Nanotechnology in Pharma',
    'Pharmacogenomics',
    'Clinical Research',
    'Regulatory Science',
    'Drug Delivery',
    'Biopharmaceuticals',
    'Personalised Medicine',
  ],
  chemsaathi: [
    'Green Chemistry',
    'Nanotechnology',
    'Computational Chemistry',
    'Material Science',
    'Drug Design',
    'Supramolecular Chemistry',
    'Astrochemistry',
    'Photochemistry',
  ],
  biosaathi: [
    'Synthetic Biology',
    'CRISPR Research',
    'Marine Biology',
    'Conservation Biology',
    'Astrobiology',
    'Neuroscience',
    'Computational Biology',
    'Genomics',
  ],
  compsaathi: [
    'Artificial Intelligence',
    'Blockchain',
    'Quantum Computing',
    'Open Source',
    'System Design',
    'Competitive Programming',
    'DevOps',
    'Startup Technology',
  ],
  archsaathi: [
    'Sustainable Architecture',
    'Smart Cities',
    'Parametric Design',
    'Heritage Conservation',
    'Urban Mobility',
    'Biophilic Design',
    'Social Housing',
    'Digital Fabrication',
  ],
  medicosaathi: [
    'Medical Research',
    'Clinical Trials',
    'Global Health',
    'Public Health Policy',
    'Medical Technology',
    'Neurology & Brain Science',
    'Oncology Research',
    'Infectious Disease',
  ],
  nursingsaathi: [
    'Community Health',
    'Palliative Care',
    'Mental Health Nursing',
    'Healthcare Policy',
    'Public Health',
    'Neonatal Care',
    'Geriatric Care',
    'Nursing Informatics',
  ],
  psychsaathi: [
    'Clinical Psychology',
    'Positive Psychology Research',
    'Behavioural Economics',
    'Neuroscience & Mind',
    'Child & Adolescent Psychology',
    'Cross-Cultural Psychology',
    'AI & Human Behaviour',
    'Social Justice & Psychology',
  ],
  mechsaathi: [
    'Robotics & Automation',
    'Renewable Energy Systems',
    'Electric Vehicles',
    'Additive Manufacturing',
    'Biomechanics',
    'Nano-materials',
    'Space Mechanisms',
    'Smart Manufacturing',
  ],
  civilsaathi: [
    'Sustainable Infrastructure',
    'Smart Cities',
    'Disaster-Resilient Design',
    'Green Buildings',
    'Urban Water Management',
    'Transportation Policy',
    'Climate Adaptation',
    'Heritage Structures',
  ],
  elecsaathi: [
    'Renewable Energy',
    'Smart Grid',
    'Electric Vehicles',
    'Power Electronics Research',
    'Energy Storage',
    'High Voltage Engineering',
    'Microgrids',
    'AI in Power Systems',
  ],
  electronicssaathi: [
    'VLSI Research',
    'IoT & Connected Devices',
    'Embedded AI',
    '5G & Beyond',
    'Wearable Electronics',
    'Photonics',
    'Quantum Electronics',
    'Neuromorphic Computing',
  ],
  chemenggsaathi: [
    'Green Process Engineering',
    'Carbon Capture',
    'Pharmaceutical Manufacturing',
    'Nanotechnology',
    'Biochemical Engineering',
    'Sustainable Fuels',
    'Process Simulation',
    'Food Technology',
  ],
  biotechsaathi: [
    'CRISPR & Gene Editing',
    'Synthetic Biology',
    'Vaccine Development',
    'Bioinformatics',
    'Industrial Biotechnology',
    'Cancer Biotechnology',
    'Agricultural Biotech',
    'Biosensors',
  ],
  aerospacesaathi: [
    'ISRO & Space Missions',
    'Satellite Technology',
    'Hypersonic Flight',
    'Space Colonisation',
    'Drone Technology',
    'Defence Aerospace',
    'Space Law & Policy',
    'Astrobiology',
  ],
  econsaathi: [
    'Development Economics',
    'Behavioural Economics',
    'Indian Economic Policy',
    'Climate Economics',
    'Global Trade',
    'Fintech & Digital Economy',
    'Inequality Research',
    'UPSC Economics Optional',
  ],
  bizsaathi: [
    'Entrepreneurship & Startups',
    'Social Enterprise',
    'Global Business Strategy',
    'Business & AI',
    'Family Business',
    'ESG & Sustainability',
    'CAT & MBA Prep',
    'Design Thinking',
  ],
  finsaathi: [
    'FinTech Innovation',
    'Sustainable Finance',
    'Cryptocurrency & Blockchain',
    'Investment Banking',
    'Financial Inclusion',
    'Behavioural Finance',
    'CFA Prep',
    'Indian Capital Markets',
  ],
  mktsaathi: [
    'Brand Strategy',
    'Social Media & Influence',
    'Consumer Psychology',
    'Marketing Analytics',
    'Rural Marketing',
    'Purpose-Driven Marketing',
    'Growth Hacking',
    'Neuromarketing',
  ],
  hrsaathi: [
    'Future of Work',
    'Diversity & Inclusion',
    'HR Technology & AI',
    'Organisational Psychology',
    'Employee Wellbeing',
    'Global HRM',
    'Labour Policy',
    'Leadership Development',
  ],
  historysaathi: [
    'Colonial & Postcolonial Studies',
    'UPSC History Optional',
    'Oral History',
    'Digital Humanities',
    'Museum & Archival Studies',
    'Partition Studies',
    'History of Science',
    'Heritage Conservation',
  ],
  accountsaathi: [
    'CA & CMA Preparation',
    'Forensic Accounting',
    'Corporate Governance',
    'Financial Fraud & Detection',
    'Accounting Technology',
    'International Accounting',
    'Startup Finance',
    'Tax Policy Research',
  ],
  polscisaathi: [
    'UPSC Political Science Optional',
    'Electoral Studies',
    'International Security',
    'Climate Diplomacy',
    'Human Rights Research',
    'Political Economy',
    'South Asian Politics',
    'Constitutional Reform',
  ],
  statssaathi: [
    'Data Science & ML',
    'Actuarial Science',
    'Biostatistics',
    'Economic Forecasting',
    'Official Statistics',
    'Spatial Statistics',
    'Sports Analytics',
    'AI & Statistical Learning',
  ],
  geosaathi: [
    'Climate Change Research',
    'UPSC Geography Optional',
    'Urban Planning',
    'Disaster Management',
    'Geopolitics',
    'Remote Sensing Research',
    'Sustainable Development',
    'Migration Studies',
  ],
  agrisaathi: [
    'Precision Agriculture',
    'Agri-Tech & Startups',
    'Food Security Policy',
    'Climate-Resilient Farming',
    'Organic Farming',
    'ICAR Research',
    'Agricultural Policy',
    'Rural Development',
  ],
  envirosathi: [
    'Climate Policy',
    'Environmental Law',
    'Renewable Energy Research',
    'Biodiversity Conservation',
    'Circular Economy',
    'Carbon Markets',
    'Environmental Justice',
    'UPSC Environment & Ecology',
  ],
  physicsaathi: [
    'Quantum Computing',
    'Astrophysics & Cosmology',
    'Particle Physics Research',
    'Condensed Matter Research',
    'Fusion Energy',
    'GATE PH & IIT JAM',
    'Optics & Photonics',
    'Theoretical Physics',
  ],
  default: [
    'Research & Academia',
    'Entrepreneurship',
    'Social Impact',
    'Policy Making',
    'International Career',
    'Sustainability',
    'Technology & Innovation',
    'Public Speaking & Leadership',
  ],
}

export function getSubjectChips(saathiId: string): string[] {
  const chips = SUBJECT_CHIPS[saathiId]
  if (!chips) {
    console.warn(`No subject chips found for saathiId: ${saathiId}`)
  }
  return chips ?? []   // return empty array — student uses "Add your own"
}

export function getInterestChips(saathiId: string): string[] {
  return INTEREST_CHIPS[saathiId] ?? INTEREST_CHIPS['default']
}
